### ISSUE TITLE
Add checker for python code

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/ci-tools#20]
Check for python syntax using one of the many linters:
- flake8
- pylint
- ..

preferably this should work on diffs rather on complete files.

**Comment by marc-hb** [comment]
BTW here's `pylint`'s most missing feature, especially in the context of focusing on new code and ignoring warnings on existing code:
```shell
usefulpylint() { pylint "$@" | sort -t ":" -k 2,2n ; }
usefulpylint -E scripts/sanitycheck
```

**Comment by ulfalizer** [comment]
Only takes ~5 seconds or so run `pylint3` on all `.py` files in the tree, so for stuff that should always generate a failure, it's easy to do that instead.

**Comment by marc-hb** [comment]
Duplicate of issue https://github.com/zephyrproject-rtos/zephyr/issues/10338 ?
